### ISSUE TITLE
As a user I can get recipes based on the ingredients I have

### ISSUE THREAD

**Issue by irismayigyu** [ohtuprojektiryhma/kitsain#1]

**Comment by irismayigyu** [comment]
Acceptance criteria: User can see the terminal application, User can use the terminal application and input ingredients, User can get a response from the application, The output is an acceptable recipe.
Started:

**Comment by SJET-Code** [comment]
## Tasks

- [x] Set up Flask API @Tuupertunut @SJET-Code 
   - [x] Takes in ingredients and gives back generated recipe
- [x] Connect to OpenAI API @SJET-Code
   - [x] Engineer a prompt so you get a valid JSON object back @SJET-Code 
- [x] Combine Flask API to OpenAI API @Tuupertunut @SJET-Code 
- [x] Research how to test APIs and write out tests @SJET-Code @Kappe01 
   - [x] Test should not cause a call to OpenAI API
- [x] User manual rough draft (API endpoints etc.) @Tuupertunut
