### ISSUE TITLE
As a user I can set conditions to the recipes eg. specific diets

### ISSUE THREAD

**Issue by irismayigyu** [ohtuprojektiryhma/kitsain#2]
Acceptance criteria: When generating recipes, the user can specify their dietary restrictions, and get recipes that fit that diet.

**Comment by SJET-Code** [comment]
## Tasks

- [x] Add an option to select the users preferred diet to the OpenAI prompt @SJET-Code
- [x] Add an users preferred diet to the Flask API post along with the ingredients @Tuupertunut @SJET-Code 
- [x] Add a selection to the test UI @erz64 @h0gm4n 
- [x] Edit user manual rough draft to include the dietary restriction option @Tuupertunut
