### ISSUE TITLE
As a user I can interact with the AI to make changes/suggestions for the result recipes

### ISSUE THREAD

**Issue by irismayigyu** [ohtuprojektiryhma/kitsain#5]

**Comment by SJET-Code** [comment]
## Tasks
- [x] Develop the API endpoints @Tuupertunut 
- [x] Add the new endpoints to documentation @Tuupertunut 
- [x] Make mock tests @Tuupertunut
