### ISSUE TITLE
As a developer, I want to test the API with a web interface

### ISSUE THREAD

**Issue by h0gm4n** [ohtuprojektiryhma/kitsain#9]
## Tasks

- [x] Create a page for inserting and submitting ingredients with Flask @erz64 @h0gm4n @SJET-Code 
- [x] Create a page for generated recipes @erz64 @h0gm4n @SJET-Code 
- [x] Utilize the change endpoint to change the latest recipe @erz64 @h0gm4n @SJET-Code
